### ISSUE TITLE
Custom poison message queue not registered in Settings QueueBindings resulting in queue not being created on AutoCreateQueue

### ISSUE THREAD

**Issue by etamm** [SzymonPobiega/NServiceBus.Raw#13]
NServiceBus.Raw version 3.2.0
.Net framework 4.7
Example program:
[ErrorQueueNotInQueueBindings.zip](https://github.com/SzymonPobiega/NServiceBus.Raw/files/4676039/ErrorQueueNotInQueueBindings.zip)

Problematic code
```
var poisonQueueName = "poision_queue";
var configuration = RawEndpointConfiguration
    .Create(
        "endpoint_name",
        (context, dispatch) => Task.CompletedTask,
        poisonQueueName);


var queueBindings = configuration.Settings.Get<QueueBindings>();

// Looking at the Create method code this should not be the case
if (!queueBindings.SendingAddresses.Contains(poisonQueueName))
{
    throw new Exception("Poison queue not bound!");
}
```

Because the poison queue name is not found in the queue bindings the queue will not be created (in my case when using MSMQ transport, but that shouldn't matter) when AutoCreateQueue is enabled.
Debugging the code it seems that this line resets the settings (or at least QueueBindings):
` Settings.PrepareConnectionString();` at [RawEndpointConfiguration.cs#L57](https://github.com/SzymonPobiega/NServiceBus.Raw/blob/2b442f209a09d2ba38c18d342ad9939dc3105e78/src/NServiceBus.Raw/RawEndpointConfiguration.cs#L57)

After that line whatever is set to `queueBindings` field won't be reflected in `Settings.Get<QueueBindings>()`.

**Comment by SzymonPobiega** [comment]
@etamm thanks for reporting it. It definitely looks like a but. I'll how I can fix it.

**Comment by SzymonPobiega** [comment]
I pushed 3.2.1 that seems to fix the issue (tested on MSMQ).
